### ISSUE TITLE
[Feature] Clarification needed for using `SolidMechanicsLagrangianFEM` with multiple target regions

### ISSUE THREAD

**Issue by francoishamon** [GEOSX/GEOSX#1140]
I am trying to run a single-phase poroelastic simulation for @AntoineMazuyer 's mesh. Antoine included multiple regions (Reservoir, Underburden, Overburden, Sea) and would like to simulate flow in Reservoir and mechanics in Reservoir, Underburden, and Overburden. I am struggling with the treatment of Sea, where we don't want to simulate anything (I removed the mesh image below because I am not sure I am allowed to use it, but I can send it on Slack)

Here is what I tried in this [file](https://totalcse.box.com/s/npxphmvwl23gz9ed1roikega3bso4noh):
  
1. If I don't define any `ElementRegion` in Sea, I get negative `localRows` in the computation of the residual norm for the mechanical problem [here](https://github.com/GEOSX/GEOSX/blob/92977f0fddf30be497e88777b25836ee9113d0af/src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp#L1115). If I guard this against `localRows` that are between 0 and `localRhs.size()` everything works well.

 2.  If I define an `ElementRegion` in Sea, then if I understand correctly, the `dofManager` defines positive `dofNumbers` in Sea, so I assume that `localRhs` and `localMatrix` will include some entries for the Sea region (which is not what I want).

@klevzoff has good suggestions of modifications that would make this case work for options 1. and 2. Thanks @klevzoff for your help.

@rrsettgast @klevzoff Should we make it clear that users have to provide a mesh in which the `solidMechanicsLagrangianFEM` solver will be applied everywhere? Or should we support the use case in which a region is not the `targetRegion` of any of the solvers?

**Comment by klevzoff** [comment]
Just to elaborate a bit more, the problem is that `SolidMechanicsLagrangianFEM` does not yet apply `targetRegions` consistently everywhere. Two specific places we've noticed in the implicit solve are:
 * `SetupDofs()`. Easy fix - just needs to pass `targetRegions` to `DofManager`.
 * `CalcualteResidualNorm()`. Easy workaround - discard local rows not in range `0..numLocalRows`, however this can conceal some bugs. Proper solution could be to maintain a list of relevant nodes to loop over (like a union of `m_nonSendOrReceiveNodes` and `m_sendOrReceiveNodes`).

If we decide to support this scenario, it would also be worthwhile adding an integrated test exercising this capability.

**Comment by francoishamon** [comment]
@klevzoff I am hitting a roadblock to solve this issue (assuming we want to allow a `subRegion` that is not `targetRegion` of `SolidMechanicsLagrangianFEM`):

I implemented the two bullets points that you suggested [here](https://github.com/GEOSX/GEOSX/blob/bugfix/hamon/issue1140/src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp), and everything works well when `SolidMechanicsLagrangianFEM` is used as a standalone solver, or in the `PoroelasticSolver` (so we can use Antoine's mesh). But, passing the target regions to the `DofManager` like this:
https://github.com/GEOSX/GEOSX/blob/abf8f83635a55971ac1ffb016c94390b77230771/src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp#L927-L930 
breaks the `HydrofractureSolver` and `LagrangianContactSolver` because they do:
https://github.com/GEOSX/GEOSX/blob/abf8f83635a55971ac1ffb016c94390b77230771/src/coreComponents/physicsSolvers/multiphysics/LagrangianContactSolver.cpp#L907-L910
and since `Fracture` is not a target region of `SolidMechanicsLagrangianFEM`, the `DofManager` throws the following error:
```
***** ERROR
***** LOCATION: /g/g90/hamon1/geosx/GEOSX/src/coreComponents/linearAlgebra/DofManager.cpp:1676
***** Controlling expression (should be false): std::find( rowRegions.begin(), rowRegions.end(), regionName ) == rowRegions.end()
***** Rank 0: Region 'Fracture' does not belong to the domain of field 'TotalDisplacement'
```
What do you think? Is there an easy fix for this?

The "partial fix" only based on your second bullet point works well in all cases. It does not break the existing integrated tests, and works when we want to ignore a `cellBlock` in the mesh (provided that no `CellElementRegion` is defined on it). 

Let me know if you think it is worth trying to fix this issue, instead of just modifying the mesh itself.

**Comment by klevzoff** [comment]
> The "partial fix" only based on your second bullet point works well in all cases. It does not break the existing integrated tests, and works when we want to ignore a `cellBlock` in the mesh (provided that no `CellElementRegion` is defined on it).

If we wanted to have some _other_ physics defined on that region, we'd be forced to declare the region and break everything again. Also, if you try to couple it with wells, `DofManager` will add `TotalDisplacement` dofs on those well nodes, because it does not discriminate between types of regions, IIRC. So the first bullet point is going to be kind of mandatory at some point. For now, though, it's a good workaround.

> What do you think? Is there an easy fix for this?

Don't have one in mind yet. Perhaps we need to rethink how dof coupling is done. Right now dofs can only interact if they have overlapping domains (in terms of element regions). This excludes some classes of coupled problems, e.g. fluid-structure interaction. The main motivator for this approach was that many things (e.g. sparsity construction) are done though element-based loops and we have to have an element list to loop over.

On the other hand, how hard would it be to include `"Fracture"` in target regions of `SolidMechanicsLagrangianFEM`? I'm not that closely familiar with the code, but from a quick look, most kernels are launched on `CellElementRegion`s only. I'm sure something would break, but may not be that difficult to fix.

**Comment by francoishamon** [comment]
Yes, it works when I add `Fracture` as a target region of `SolidMechanicsLagrangianFEM`, thanks for the suggestion. It actually does not break anything when the `Fracture` region has a `rock` material in the list of constitutive models. I can pass the integrated tests with no numerical diffs. I will do a PR to see what you and others think of the changes. Thanks!
