### ISSUE TITLE
[Bug] integratedTests/compositionalMultiphaseFlow/CO2_flux_3d.xml

### ISSUE THREAD

**Issue by tang39** [GEOSX/GEOSX#1191]
There is a typo when defining source and sink
Should be 26.99, not 27.99
Should be  3.01 , not 2.01

**Comment by francoishamon** [comment]
Hello @tang39,
Thanks for reporting this. You are right, this is a bug in the setup of the problem. It will be fixed by PR #1155, where the change is made: 
https://github.com/GEOSX/GEOSX/blob/5809a76d1b7d9342882668786ab4acfcbd13b74e/src/coreComponents/physicsSolvers/fluidFlow/integratedTests/compositionalMultiphaseFlow/co2_flux_3d.xml#L40-L47
