### ISSUE TITLE
[Feature] Well group control (manifold) boundary condition

### ISSUE THREAD

**Issue by tang39** [GEOSX/GEOSX#1193]
**What is the requested feature?**
This is a boundary condition that commonly appears in reservoir management problems. Saying multiple wells are connected by a manifold so that a fixed injection/production rate distributed among all these wells based on mobility at the well location. Each well is constrained by a maximum/minimum pressure as well. 
 
**Is your request related to a specific problem?**
Yes. My case has four injection wells injecting under a constant total injection rate. If pressure of any individual well exceeds the maximum injection pressure constraint, this well will switch to bottomhole pressure control
 
**Describe the solution you'd like**
An ideal solution is to not use the multisegment well module. Isaac @IsaacJu-debug  has done such a trick in GEOS to handle this. He defines these wells as source fluxes under a same name in the input (treat as a single well). He has included well calculations to source element and implemented a checker for pressure to switch between the boundary conditions.  I am not sure whether the same trick is feasible in GEOSX with SourceFlux or any other elements. 
 
**Describe alternatives you've considered**
Extending the multisegment well to surface facility will automatically handle this boundary condition. This might be more time consuming.

@cssherman @PengchengFu4

**Comment by francoishamon** [comment]
I see two possibilities to achieve what you are trying to do:

**1) With boundary conditions:**
Currently the `SourceFlux` boundary condition (implemented [here](https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFlow.cpp#L946)) adds a pre-determined amount of mass of a given component into the target cells. An XML example using this feature is [here](https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/sourceFlux_2d.xml#L195). It currently does not take into account the mobility of the reservoir cells and just injects the amount of mass defined in the XML file. As for the (cell-centered) pressure boundary condition, it imposes a predefined pressure value in the cell (so it is not exactly similar to a BHP constraint and does not output a rate). Therefore, to implement what you suggest using the boundary condition mechanism, you would have to:

- Modify `CompositionalMultiphaseFlow::ApplySourceFluxBC` so that it accounts for the mobility in the reservoir cell to determine dynamically the amount of mass injected in the cell.
- If you want the switch in boundary conditions to happen between the nonlinear iterations, modify `CompositionalMultiphaseFlow::ApplyBoundaryConditions` to add a switch that would enforce a pressure boundary condition if the pressure threshold is met, and a source flux boundary conditions if not.
- If you want to switch to happen between time steps, it is probably easier to define some kind of conditional `Event` in the XML file that would kick in if the pressure threshold is met. This is simpler, especially if the pressure constraint is a "soft" constraint and if you take small time steps. @cssherman how can we do that?
- Once the control has switched to pressure control, you have to modify `CompositionalMultiphaseFlow::ApplyDirichletBC` to compute an injection rate for the total injection rate constraint. I am not sure how you would to do that because you need a pressure difference in the usual Peaceman model, and with a pressure boundary condition you directly impose a pressure value in the reservoir cell. @tang39 @IsaacJu-debug how did you do that in GEOS?

**2) With wells:**
There is currently no group constraint on the well rate in GEOSX, but only individual rate and pressure constraints. However, the mobility of the reservoir cell is taken into account for the computation of the rates, and there is a true BHP control implemented (i.e. we do not directly enforce the reservoir cell pressure as done with pressure boundary conditions). To achieve what you want to do, we would have to:

- Gather all the injection rates computed in `CompositionalMultiphaseWell::ComputeAllPerforationRates` ([here](https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp#L418)) to compute the total injection rate across all wells.
-  Modify the assembly of the constraint in `CompositionalMultiphaseWellKernels::ControlEquationHelper` ([here](https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWellKernels.hpp#L38)) as well as the control switch in the same location.

This is something I will have to do as some point anyway to match simulation results from industrial simulators. 

While the changes in the well assembly are not difficult to implement, one potential complication to keep in mind with the well route is that the group constraint will couple all the well blocks together in the linear systems, which may alter the performance of our current MGR recipe (see the current implementation [here](https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp#L408)).

**Comment by cssherman** [comment]
@tang39 @francoishamon - this is certainly possible.  We could create a task that is designed to toggle an object flag based upon the min/max values of a target and/or the results of a function.

For PeriodicEvents, this sort of behavior is already present (although not commonly used).  If an optional function/target is specified, when the time/cycle frequency criteria are met, the event will evaluate the function, and if the result is above a specified threshold the event will execute.

**Comment by tang39** [comment]
@cssherman  I currently use the CompositionalMultiphaseWell option. To achieve the group control of four wells in a 2D setting.  I define the well like following with a total target rate and BHP control. It works well so far for some simple testing cases:
a ------ b
             |
d ------ c

**Comment by francoishamon** [comment]
Closed as not planned in the short term
