### ISSUE TITLE
[Feature] Time history for quantities not registered on the mesh

### ISSUE THREAD

**Issue by francoishamon** [GEOSX/GEOSX#1205]
**What is the requested feature?**
In PR #1202, I would like to use the time history capability to output some quantities that are not registered on the mesh, but that are instead registered on the solvers. It would be useful to me to output some dynamic quantities used to control the wells by doing:
```
<PackCollection                                                                                                               
  name="wellBHPCollection1"                                                                                          
  objectPath="Solvers/compositionalMultiphaseWell/wellControls1"                                                             
  fieldName="currentBHP" />
```
When I try that I get the following error:
```
***** ERROR                                                                                                                                   
***** LOCATION: /g/g90/hamon1/geosx/GEOSX/src/coreComponents/managers/TimeHistory/PackCollection.cpp:149                                      
***** Controlling expression (should be false): targetGroup == nullptr                                                                        
***** Rank 0: PackCollction::getTargetObject( ): Last entry in objectPath (/Solvers) is not found 
```

and my understanding is that the current implementation assumes that the desired quantity is under `MeshLevel`:
https://github.com/GEOSX/GEOSX/blob/d938407081613958ed1b02672c3bd6ae4aaf28d8/src/coreComponents/managers/TimeHistory/PackCollection.cpp#L124-L127

One possibly more interesting use case would be to use the time history to plot the nonlinear iterations count as a function of time, and for this I assume we would also need the ability to plot quantities not registered on the mesh.

**Describe the solution you'd like**
@wrtobin If I understood well that we currently cannot output quantities not registered on the mesh, do you think it is possible to modify the `PackCollection` class to allow this use case?

**Describe alternatives you've considered**
The workaround for the well example posted here is simply to register the dynamic controls (BHP, etc) on the mesh, so this issue is not blocking.

**Comment by wrtobin** [comment]
@francoishamon 

Yeah it should be entirely possible to grab values not on the mesh as long as they are registered with Groups/Wrappers in the dataRepository.

Practically, the member function that gets the target object should probably be pulled into the `TimeHistoryCollection` superclass, and the change to the lookup should happen there. The `PackCollection` class should be able to collect the desired terms and output them -- most likely without any additional changes.

**Comment by francoishamon** [comment]
We have another good use case for the time history output for quantities not registered on the mesh:

In the wave propagation solver that @mndiaye24 is developing (see #1269 ), the `AcousticWaveEquationSEM` defines a small number of "receivers" (a few points in the mesh defined by their (x,y,z) coordinates) and saves an interpolated pressure value at each receiver after each explicit step. My understanding is that the number of receivers is going to remain small, and that in general it will be difficult to know before the simulation where these receivers are (this would require a pre-processing of the mesh). It would be great to be able to output in a hdf5 file these interpolated pressure values as a function of time.

We tried various things to make this work by registering the receiver pressures on the element sub-regions (such as resizing the receiver pressure array so that it does not scale with the number of cells) without much success, so I think it would just be much easier if we could directly output quantities registered on a physics solver. 

@wrtobin how do you want to proceed for this issue? If we add a possibility to search for wrappers in the physics solvers as you suggest above to replace what is done here:
https://github.com/GEOSX/GEOSX/blob/d938407081613958ed1b02672c3bd6ae4aaf28d8/src/coreComponents/managers/TimeHistory/PackCollection.cpp#L124-L127
do you think it is going to work "automatically"? Let me know if you want me to help.

**Comment by wrtobin** [comment]
@francoishamon 

Yeah it should be entirely possible to target anything registered in the data repository, and as long as the `WrapperBase::getHistoryMetadata()` is able to produce the correct metadata for the wrapped type, it should be written to the hdf5 file correctly. The implementation of the standalone function `getHistoryMetadata` in `HistoryDataSpec.hpp` defines what is collectable by the time history and includes most scalar types and collections of scalar types.

Currently the assumption is that the data repo address provided to the collector is a mesh object, so it starts looking down the path from the mesh to groups/wrappers it contains. If we change it so that the path provided is an absolute path instead of an assumed relative path from the mesh, we'll probably need to change any existing time history xml specs in the tutorials/elsewhere in order to accommodate the change.

If we want to retain the existing functionality (and not change the existing xml) we could add a new xml element to specify explicitly the path is absolute, or to provide a prefix for non-absolute paths that defaults to the mesh if it isn't specified, it might also be possible just to check that if the path starts with a '/' it's absolute, otherwise it is assumed relative from the mesh. Not sure I like the '/' mechanism since it is a bit less explicit to the user, but it doesn't seem entirely unreasonable.

**Comment by francoishamon** [comment]
This has been addressed and can now be done for vector quantities
