### ISSUE TITLE
[Feature] TableFunctions applied on device

### ISSUE THREAD

**Issue by cssherman** [GEOSX/GEOSX#1232]
**What is the requested feature?**
We should adapt/test TableFunctions to work on device.

**Comment by francoishamon** [comment]
Hello @cssherman and @klevzoff, 
We have a good use case for reading a relative permeability table from file now (a input deck recently received with relperm tables that cannot be matched easily with an analytical model) so it is probably a good time to address issue #1226. I am trying to understand what would be a good plan to be able to use the table functions on device to update the relperms. 

1) To get the table functions working on device, would we have to modify the entire Functions interface, including `FunctionBase` and all the derived classes? Or can we just modify the `TableFunction` class?

2) If the answer to 1) is that we can just modify `TableFunction`, I would like to start the discussion by proposing what I would (naively) do, say, for a two-phase relperm model updated on device:

a) I would create a relative permeability model deriving `RelativePermeabilityWithTable` inheriting from `RelativePermeabilityBase` with two `m_tableFunction` data members of type `TableFunction` (one for each phase) that would be filled at initialization with the input provided by the user. 

b) Then for the relative permeability update on device, I would first instantiate a `KernelWrapper` for the new model in `CompositionalMultiphaseFlow` just before the kernel launch (where it is currently instantiated for the other models). The function doing the kernel creation would look like (assuming below: `using KernelWrapper = RelativePermeabilityWithTableUpdate;`):
```
RelativePermeabilityWithTable::KernelWrapper RelativePermeabilityWithTable::createKernelWrapper()
{
  arrayView1d< real64 const > & tableCoordsOil = m_tableFunctionOil.getCoordinates(); 
  arrayView1d< real64 const > & tableValuesOil = m_tableFunctionOil.getValues(); 
  arrayView1d< real64 const > & tableCoordsWater = m_tableFunctionWater.getCoordinates(); 
  arrayView1d< real64 const > & tableValuesWater = m_tableFunctionWater.getValues(); 

  return KernelWrapper(  tableCoordsOil,
                         tableValuesOil,
                         tableCoordsWater,
                         tableValuesWater,
                         m_phaseTypes,
                         m_phaseOrder,
                         m_phaseRelPerm,
                         m_dPhaseRelPerm_dPhaseVolFrac );
}
```
where the `RelativePermeabilityWithTableUpdate` class would be similar to the other `...Update` classes for the relperm models we have already implemented, with four data members:
```
class RelativePermeabilityWithTableUpdate  final : public RelativePermeabilityBaseUpdate
{     
    GEOSX_HOST_DEVICE
    GEOSX_FORCE_INLINE
    virtual void Compute( arraySlice1d< real64 const > const & phaseVolFraction,
                          arraySlice1d< real64 > const & phaseRelPerm,
                          arraySlice2d< real64 > const & dPhaseRelPerm_dPhaseVolFrac ) const override;
   
    [...]

    arrayView1d< real64 const > m_tableCoordsOil;
    arrayView1d< real64 const > m_tableValuesOil;
    arrayView1d< real64 const > m_tableCoordsWater;
    arrayView1d< real64 const > m_tableValuesWater;
};
```
c) Then in `RelativePermeabilityWithTableUpdate::Compute` I would do:
```
RelativePermeabilityWithTableUpdate::Compute( ... )
{
    // [...] get the oil saturation in oilSaturation
    TableFunction::Evaluate1D( m_tableCoordsOil,
                               m_tableValuesOil,
                               oilSaturation,
                               oilRelperm,
                               dOilRelPerm_dOilSat );
    // [...] another call for the water phase
}
```
d) To make that work, I would implement the following static function in the `TableFunction` class:
```
GEOSX_HOST_DEVICE
static void
TableFunction::Evaluate1D( arrayView1d< real64 const > & tableCoords,
                           arrayView1d< real64 const > & tableValues,
                           real64 const & inputValue,
                           real64 & functionValue,
                           real64 & functionDerivativeValue )
{
   // interpolate linearly using tableCoords and tableValues and fill functionValue and functionDerivativeValue
}
```
This function would be specialized for 1D interpolation and we could reuse it elsewhere (CO2-brine interpolation, maybe PVT Package). Hopefully what is above makes a little bit of sense. I am sure there is a better way! Please let me know.

**Comment by klevzoff** [comment]
Hi @francoishamon , I more or less agree with the proposed plan. I don't think we should try to change `FunctionBase` virtual interface at this time. Just a couple things to consider:
  1. Whether the tables should be defined in the XML inline with the model or separately via `FunctionManager` - I seem to remember us discussing this issue with contact models, but forgot what the decision was.
  2. It'd be nice if all implementation details of a table function (such as coordinate/value array views) were encapsulated inside a device-friendly `TableFunctionKernelWrapper` (or some better name, perhaps). So `RelativePermeabilityWithTableUpdate` would contain instance(s) of that class rather than raw array views.
  3. It would be really great if we could avoid implementation divergence between existing virtual and new gpu-friendly interfaces. To that end, I suggest we try to adapt existing multilinear interpolation code in `TableFunction::Evaluate()` to gpu. This should involve, as far as I can tell, just changing uses of `std::lower_bound` to a binary search already implemented somewhere in LvArray, and possibly changing `TableFunction::m_coordinates` to be `LvArray::ArrayOfArrays` - although I'm not certain this is required. We can also make it return derivatives (at least for "Linear" method, where it is well-defined).  This code can reside in `TableFunctionKernelWrapper` with roughly the following signature:
```c++
template< typename IN_ARRAY, typename OUT_ARRAY >
GEOSX_HOST_DEVICE void
TableFunctionKernelWrapper::Compute( IN_ARRAY const & input, real64 & value, OUT_ARRAY && derivatives )
```
(template parameters are just for flexibility, could also be hardcoded to use `arraySlice1d`). `TableFunction::Evaluate()` could then just forward to an instance of `TableFunctionKernelWrapper` pre-constructed and stored inside a `TableFunction` object (and drop the derivatives), while your relperm kernel wrapper will call to its own instances.

I hope this makes sense. That said, there may be performance benefits to specializing 1D interpolation, and we can discuss that further - I'm not opposed to the idea. Other than that, I would maybe call the model `TableRelativePermeability` or `TableBasedRelativePermeability` (purely personal aesthetic choice, to keep it stylistically similar to `BrooksCorey` and others).

**Comment by cssherman** [comment]
@klevzoff - your approach sounds like a great idea.  I haven't been involved in any of the GPU algorithm porting so far, so I'd definitely defer to your judgement there.  

We should try our best to avoid a specialized 1D function.  In legacy GEOS, there was a lot of function specialization, which invariably led to the >1D table functions being ignored in optimizations/bugfixes/documentation.

**Comment by rrsettgast** [comment]
Regarding the GPU performance of a table lookup, and thread divergence specifically...Would it make sense to generate an equal spaced table which would result in a trivial non-divergent operation for the lookup? For instance, if we had a equal spaced option and we wanted a lookup at some floating point value `x`, there would be a multiply (really a division, but we can store the inverse of the interval size), and conversion to integer, and then we have the index to get the value...and then we need an interpolation. Does this make sense for the use case?

**Comment by klevzoff** [comment]
> Regarding the GPU performance of a table lookup, and thread divergence specifically...Would it make sense to generate an equal spaced table which would result in a trivial non-divergent operation for the lookup? For instance, if we had a equal spaced option and we wanted a lookup at some floating point value `x`, there would be a multiply (really a division, but we can store the inverse of the interval size), and conversion to integer, and then we have the index to get the value...and then we need an interpolation. Does this make sense for the use case?

Yes, it would be a really nice optimization. Not all tables should have this, as sometimes the user-provided spacing is important (e.g. log-spaced coordinates) and sometimes we strive for a close match vs a commercial simulator which could require preserving input tables as is. But probably a majority of cases, and especially for most rel-perm tables where the coordinate space is [0..1] this could be a net benefit.
