### ISSUE TITLE
Investigate breaking up CI testing into separate compilation and testing stages.

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#1349]
**What is the requested feature?**
We currently compile and run unit tests in the same CI stage. If we fail a unit test we have to inspect the log, and find the failure in either the actual build, or the test phase. Also, if we wanted to debug a unit test failure in a travisCI VM, this would require us to wait for the build, then address the unit test failure.

It would be nice to separate the build and test phases, but this requires some sort of external storage since all the phases are new VM's. 
https://docs.travis-ci.com/user/build-stages/#data-persistence-between-stages-and-jobs

Can we investigate separating out the stages?

**Comment by TotoGaz** [comment]
Hi @rrsettgast, I'm already quite long-term booked with multiple items and I have no time in 2021 for such consistent and technical action (This would change a lot the global flow; it's more complex than it looks and a lot of details need to be considered).
If you think that this issue is really worth it please argue with @herve-gross to trade in/trade out my backlog; I cannot.
I therefore retract myself from this issue.

**Comment by rrsettgast** [comment]
@TotoGaz I wasn't really assigning the issue to you. It was more of an assignment of consulting on the topic. I would expect that Brian could look into this as he has done a lot of work in the recent past on getting the Travis workflow much more streamlined.

**Comment by TotoGaz** [comment]
@rrsettgast OK no problem. This is a really challenging task that will last for loooong.
Personally, I'm not sure that we really have a strong use case that cannot be solved by downloading the docker env on a box.
And if we have one, it should be really rare. Do you have concrete examples? Maybe the Pangea2 tests but I haven't tried to reproduced them yet.
