### ISSUE TITLE
Display local fluid velocity

### ISSUE THREAD

**Issue by sytuannguyen** [GEOSX/GEOSX#1370]
**What is the requested feature?**
Display local fluid velocity

**Is your request related to a specific problem?**
When running an operational flow problem, we want to display the local fluid velocity to demonstrate that fluid is flowing into a well. Unfortunately, this feature is not available yet in GEOSX.

**Comment by klevzoff** [comment]
Right now velocity is computed in-kernel from primary fields (e.g. pressure) and immediately used for assembly. Moreover, it is a  (scalar) interface velocity, rather than a (vector) cell-centered velocity that is easier to visualize. Reconstructing a cell-centered velocity field would require accessing the mesh geometry again (face/cell centers). Something like this is done in proppant transport solver, where flow direction influences particle settling. This has impact on required memory footprint on GPU, especially for multiphase problems, so we should be careful.

My suggestion would be to add a separate kernel to compute cell-centered phase velocity and/or flux (we should decide which quantity we actually want). It should only run at time step completion, and ideally it should be optional - probably with an input flag that enables it (can be on by default, as long as there's a way to turn it off).

**Comment by francoishamon** [comment]
Hi @sytuannguyen 
There is already something similar to this in the code (cell-centered phase/component outflux and CFL number)
It is here: https://github.com/GEOSX/GEOSX/blob/42190c68b77092dca60128f2e8a3804989c110a6/src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp#L126
and in the lines above.
Please re-open another issue if it does not meet your needs
