### ISSUE TITLE
[Bug] Fail to set well rate control

### ISSUE THREAD

**Issue by wdmhouston** [GEOSX/GEOSX#1447]
**Describe the bug**
Try to set well control to "totalVolRate" without targetBHP and GEOSX gives error: targetBHP is required. This doesn't make sense. targetBHP should not be marked as required in rate control mode.

test dataset is attached.
[test.zip](https://github.com/GEOSX/GEOSX/files/6563875/test.zip)

````
<WellControls
        name="wellControls"
        type="injector"
        control="totalVolRate"
        useSurfaceConditions="1"
        surfacePressure="101325"
        surfaceTemperature="15.56"
        referenceElevation="29.81096"
        targetTotalRate="7.64"
        injectionStream="{ 1.0, 0 }"/>
````

Error message:
````
user@ubuntu:/data/final1_rate$ geosx -i CO2.xml
Adding Solver of type CompositionalMultiphaseReservoir, named coupledFlowAndWells
Adding Solver of type CompositionalMultiphaseFVM, named compositionalMultiphaseFlow
Adding Solver of type CompositionalMultiphaseWell, named compositionalMultiphaseWell

***** LOCATION: /apps/GEOSX/src/coreComponents/dataRepository/Wrapper.hpp:708
***** Controlling expression (should be false): !m_successfulReadFromInput
***** Rank 0: Input variable targetBHP is required in /Problem/Solvers/CompositionalMultiphaseWell/WellControls. Available options are:
  |         name         |  opt/req  | Description
  |----------------------|-----------|-----------------------------------------
  |            targetBHP |  REQUIRED | Target bottom-hole pressure

For more details, please refer to documentation at:
http://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/userGuide/Index.html


** StackTrace of 9 frames **
Frame 0: geosx::dataRepository::Group::processInputFile(pugi::xml_node const&)
Frame 1: geosx::dataRepository::Group::processInputFileRecursive(pugi::xml_node&)
Frame 2: geosx::dataRepository::Group::processInputFileRecursive(pugi::xml_node&)
Frame 3: geosx::dataRepository::Group::processInputFileRecursive(pugi::xml_node&)
Frame 4: geosx::dataRepository::Group::processInputFileRecursive(pugi::xml_node&)
Frame 5: geosx::ProblemManager::parseInputFile()
Frame 6: geosx::GeosxState::initializeDataRepository()
Frame 7: main
Frame 8: __libc_start_main
Frame 9: _start
=====

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
````

**To Reproduce**
run test dataset.

**Expected behavior**
well is set to rate control mode.

**Screenshots**
n/a

**Platform (please complete the following information):**
Machine: Ubuntu
Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
GEOSX Version:0.2.0

**Comment by wdmhouston** [comment]
When targetBHP is added back to well control and keep well control mode as totalVolRate, GEOSX will run, but well control is still set to pressure control mode(observed from well pressure and rate in hd5 files).

````
      <WellControls
        name="wellControls"
        type="injector"
        control="totalVolRate"
        useSurfaceConditions="1"
        surfacePressure="101325"
        surfaceTemperature="15.56"
        referenceElevation="29.81096"
        targetBHP="18522627.57"
        targetTotalRate="7.64"
        injectionStream="{ 1.0, 0 }"/>
````
![image](https://user-images.githubusercontent.com/19333848/120054416-6b1eb780-bff5-11eb-83c6-c44ba5fe7741.png)

This is a bug, and please fix.

Any quick workaround? 


Regards,

Deming

**Comment by francoishamon** [comment]
Sorry about the clunky well input, it needs to be documented / improved. 
This input:
```
<WellControls
        name="wellControls"
        type="injector"
        control="totalVolRate"
        useSurfaceConditions="1"
        surfacePressure="101325"
        surfaceTemperature="15.56"
        referenceElevation="29.81096"
        targetBHP="18522627.57"
        targetTotalRate="7.64"
        injectionStream="{ 1.0, 0 }"/>
```
means that you inject CO2 at a total rate of 7.64 m^3.s^-1 at surface conditions, with the constraint that the BHP should be smaller than 18522627.57 Pa. If/when the BHP pressure reaches this value, the active control switches from total rate to BHP.

If at some point, you create an input file with `control="BHP"` but keep everything else the same, it will mean that you inject CO2 at a BHP of 18522627.57 Pa, with a maximum volumetric rate of 7.64 m^3.s^-1. 

In your current input file, it is possible that the well switches control from rate to BHP at initialization, or very early in the simulation, or later. To figure this out, you go to the output of the simulation, and you search for a message saying that the well has switched control. This message should be there because you have put `logLevel="1"` in `CompositionalMultiphaseWell` in your input file.

Other comments:
- The temperature for `CompositionalMultiphaseFVM` and `CompositionalMultiphaseWell` should be provided in Kelvin, so `temperature="35"` may create some issues when the CO2 and brine properties are computed (even if the temperature is always assumed to be constant in space and time for now in GEOSX). Quick suggestion: put 368.5 K to have something consistent with the values that you have in `co2flash.txt` (which are in Celsius, we need to fix that,sorry), or change the values of temperature in the PVT files. See https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/constitutive/docs/CO2Brine.html#
- With your current input, the well is going to try to evaluate the CO2 density at the surface pressure and surface temperature, which are out of the tables generated internally using the bounds provided in `co2flash.txt`. See the link I provided above. So my suggestion for the well control is:
```
<WellControls
        name="wellControls"
        type="injector"
        control="totalVolRate"
        referenceElevation="50" <<--- based on what I saw in the well definition in your file
        targetBHP="18522627.57"
        targetTotalRate="7.64"
        injectionStream="{ 1.0, 0 }"/>
```

**Comment by wdmhouston** [comment]
I see. let me fix my dataset and try again.


Regards,

Deming

**Comment by francoishamon** [comment]
I am closing this issue, let me know if the well input I proposed does not work.

**Comment by wdmhouston** [comment]
> I am closing this issue, let me know if the well input I proposed does not work.

Thanks. Please close it.
