### ISSUE TITLE
[Feature] Output key quantities on the fracture surfaces

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1496]
**What is the requested feature?**
Systematically output key quantities on the fracture surfaces (e.g., aperture, shear slip magnitude and stress), which are projected in the local coordinate system.

**Is your request related to a specific problem?**
As for the following case, the relative displacement along the crack plane is difficult to compute in postprocessing:
src/coreComponents/physicsSolvers/multiphysics/integratedTests/ContactMechanics_UnstructuredCrack.xml
The lineout query function in Visit does not work properly as the crack surface is not a straight-line and node information is hard to track with unstructured mesh.

**Additional context**
This request can be extended to multiple geological features (fault, fracture, folding layers....).

**Comment by joshua-white** [comment]
@jhuang2601, it seems this issue is partially resolved via our TimeHistory capabilities (which can query some temporary fields we aren't outputting by default), right? Just making a note here for future users.  Could you briefly describe your solution?

We should leave this issue open, though, as I think we want a more systematic look at our fracture / fault viz data.
