### ISSUE TITLE
[Bug] Time history output for multi-component quantities (array2d, etc)

### ISSUE THREAD

**Issue by francoishamon** [GEOSX/GEOSX#1510]
**Describe the bug**
I am trying to use the time history output feature to output the saturation (`phaseVolumeFraction`, stored in an array2d) into an hdf5 file. GEOSX crashes with the following stack trace message:
```
** StackTrace of 12 frames **                                                                                                                  
Frame 0: LvArray::system::stackTraceHandler(int, bool) /g/g90/hamon1/geosx/GEOSX/src/coreComponents/LvArray/src/system.cpp:478 (discriminator 1)                                                                                                                                             
Frame 1: /g/g90/hamon1/geosx/GEOSX/build-quartz-gcc@8.1.0-debug/bin/geosx /g/g90/hamon1/geosx/GEOSX/src/coreComponents/common/initializeEnvironment.cpp:82                                                                                                                                   
Frame 2: /g/g90/hamon1/geosx/GEOSX/build-quartz-gcc@8.1.0-debug/bin/geosx /g/g90/hamon1/geosx/GEOSX/src/coreComponents/common/initializeEnvironment.cpp:82                                                                                                                                   
Frame 3: /lib64/libc.so.6                                                                                                                      
Frame 4: geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> const&, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> const&, std::vector<camp::resources::v1::HostEvent, std::allocator<camp::resources::v1::HostEvent> >&)::{lambda(long)#1}::operator()(long) const::{lambda(double const&)#1}::operator()(double const) const /g/g90/hamon1/geosx/GEOSX/src/coreComponents/dataRepository/BufferOpsDevice.cpp:173                                                                                                                                        
Frame 5: void LvArray::forValuesInSlice<double const, geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> const&, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> const&, std::vector<camp::resources::v1::HostEvent, std::allocator<camp::resources::v1::HostEvent> >&)::{lambda(long)#1}::operator()(long) const::{lambda(double const&)#1}&>(double const&, geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> const&, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> const&, std::vector<camp::resources::v1::HostEvent, std::allocator<camp::resources::v1::HostEvent> >&)::{lambda(long)#1}::operator()(long) const::{lambda(double const&)#1}&) /g/g90/hamon1/geosx/GEOSX/src/coreComponents/LvArray/src/sliceHelpers.hpp:32                                                                                      
Frame 6: void LvArray::forValuesInSlice<double const, 1, 0, long, geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> const&, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> const&, std::vector<camp::resources::v1::HostEvent, std::allocator<camp::resources::v1::HostEvent> >&)::{lambda(long)#1}::operator()(long) const::{lambda(double const&)#1}>(LvArray::ArraySlice<double const, 1, 0, long>, geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> const&, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> const&, std::vector<camp::resources::v1::HostEvent, std::allocator<camp::resources::v1::HostEvent> >&)::{lambda(long)#1}::operator()(long) const::{lambda(double const&)#1}&&) /g/g90/hamon1/geosx/GEOSX/src/coreComponents/LvArray/src/sliceHelpers.hpp:50 (discriminator 2)                        
Frame 7: geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> const&, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> const&, std::vector<camp::resources::v1::HostEvent, std::allocator<camp::resources::v1::HostEvent> >&)::{lambda(long)#1}::operator()(long)const /g/g90/hamon1/geosx/GEOSX/src/coreComponents/dataRepository/BufferOpsDevice.cpp:171 
Frame 8: RAJA::policy::omp::forall_impl<RAJA::TypedRangeSegment<long, long>, geosx::bufferOps::PackDataByIndexDevice<true, double, 2, 1, LvArray::ArrayView<long const, 1, 0, long, LvArray::ChaiBuffer> >(signed char*&, LvArray::ArrayView<double const, 2, 1, long, LvArray::ChaiBuffer> 
srun: error: quartz5: task 0: Segmentation fault (core dumped)
```

**To Reproduce**
1. Checkout `develop`
2. Run the problem attached
[bug.zip](https://github.com/GEOSX/GEOSX/files/6864956/bug.zip)

**Expected behavior**
It should work fine

**Platform:**
- LLNL/Quartz
-  gcc 8.3.1 debug
- Current `develop`

**Additional context**
If I replace `phaseVolumeFraction` by `phaseMobility` (another multi-component array), I get the same crash. If I replace `phaseVolumeFraction` by `pressure` or `phaseCFLnumber` (one-component arrays), the simulation works fine. That seems to indicate that there is a problem related to multi-component arrays. @wrtobin do you know what may be going on?

**Comment by wrtobin** [comment]
I'll take a look at this as asap.

**Comment by wrtobin** [comment]
I've recreated this on quartz with gcc and clang.

The `phaseVolumeFraction` array has initial size of `(100,0)`. 

We're currently able to deal with arrays where the unknown is the number of items in the first index (the element index, node index, etc), but where the additional dimensions are known, since those additional dimensions constitute a discrete unit of data for output by hdf5 and are currently required to initialize and write to the data file. I'm currently trying to think of the easiest way around this. Either:

1.  Ensuring these arrays are initialized to the appropriate size prior to initialization of the time history output/collection would probably fix the issue immediately; or 
2.  I'll  have to modify the hdf5 file writer to account for the additional dynamic dimensions... this will take at least a day or two.

This is why if the an old version of the output file is removed prior to a run, hdf5 prints errors to the screen during init, an existing output file checks that the dataset exists (which it does, just without an extent), and on restart that the number of collected history events is correct, but not currently dimensions beyond that (esp since the number of indices can change over time).

**Comment by wrtobin** [comment]
We collect the coordinates and cell-centers automatically, which IIRC are both stored in array2Ds with known 2nd dimensions and do not have this issue, which lends credence to my thinking that ensuring the size doesn't contain a zero other than in possibly the first dimension (which is supported) would resolve the issue.

**Comment by klevzoff** [comment]
The problem seems to be that field resizing in the flow solver happens during `ProblemManager::initialize()` sequence, which is also where `PackCollection` gets initialized, and there is no guaranteed order between the two. 

@francoishamon We might be able to move field resizing from `initializePreSubGroups()` into `registerDataOnMesh()` with some caution - the constitutive models on the subregions already exist at that point, so the relevant dimensions can be extracted. This would solve the problem.

**Comment by wrtobin** [comment]
Currently groups just directly iterate over their subgroups to initialize, but `initializationOrder` could be used to provide an constrained order for initialization to satisfy dependencies such as this. Time history should probably be near the end of the order somewhere.

**Comment by francoishamon** [comment]
Ok thanks @wrtobin @klevzoff I will give it a try.
