### ISSUE TITLE
develop segfault/double free errors in unit tests using clang10

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#1802]
**Describe the bug**
develop now contains segfaults, and double free corruptions when running unit tests using clang10-release on quartz. Probably has to do with the recent python work that was merged into develop.

**To Reproduce**
run unit tests using clang10 release build. `testWrapper` is a simple one that fails.

**Expected behavior**
no memory corruptions

**Comment by labesse40** [comment]
I compiled GEOSX with Clang10 on my laptop and managed to fix the issue. The problem was coming from the dependency being on `pygeosx` in the unitTests, and is similar to what @sframba described. I modified it to depend on the different structures (`pygroup, pyfileIO, pysolver`). All tests are now working on my laptop. Could you test it on Quartz since I don't have access to it ?  I made a PR for this issue [#1807 ](url)
