### ISSUE TITLE
[Other] Crash when using imported mesh with only pyramid elements

### ISSUE THREAD

**Issue by alexandrebtessael** [GEOSX/GEOSX#1841]
Hello. I tried to use an imported mesh with xMin = (0,0,0) and xMax = (1,1,1) named pyramid_2x2x2_crash.msh. It is composed only of pyramids and is used to perform geomechanics simulation. I received an error message when running the file (see screenshot below).

To correct it, I had to add +1 to every coordinate of each point in order to get rid of this error. So the version working is with xMin =
(1,1,1) and xMax = (2,2,2) (mesh name is pyramid_2x2x2_no_crash.msh). There is no other modification.

I performed a similar test with a mesh composed of only 1 pyramid (1_pyra_crash.msh) with xMin = (0,0,0) and xMax = (0.5,0.5,0.5). Again, I observe the same error and to correct it, I added +1 to the X-coordinates of every node (1_pyra_no_crash.mesh).

It seems that the crash was in the Jacobian computation was due to the flat quad in the pyramids.
The link to the files is : https://filesender.renater.fr/?s=download&token=ef9a4905-131f-41cc-a491-b5385853ac00

![image](https://user-images.githubusercontent.com/87317386/159701073-e183b4b9-29c3-44f4-99ac-388836bbdfe0.png)

**Comment by castelletto1** [comment]
Hi @alexandrebtessael. The problem is a wrong ordering assumption when importing pyramids. #1866 resolves this issue. I diagnosed the problem by running the finite element unit test for pyramids using the coordinates from `1_pyra_crash.msh`, provided in the order expected by GEOSX (see [here](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/finiteElement/elementFormulations/H1_Pyramid_Lagrange1_Gauss5.hpp))

https://github.com/GEOSX/GEOSX/blob/1dfd7fdf08430dac5e605b10c3a0ada99f7fc590/src/coreComponents/finiteElement/unitTests/testH1_Pyramid_Lagrange1_Gauss5.cpp#L49-L54

Below are slightly modified versions of the xml files available at the link above, which now run successfully.

[pyramids_xml.zip](https://github.com/GEOSX/GEOSX/files/8396790/pyramids_xml.zip)
