### ISSUE TITLE
[Other] Cannot install geosx_xml_tools on Ubuntu

### ISSUE THREAD

**Issue by bigmonsterlee** [GEOSX/GEOSX#1882]
I encountered some problem in installing geosx_xml_tools on Ubuntu:

Could not find where preprocess_xml is installed.Could not find where format_xml is installed

root@qingqing:/bishe/codes/GEOSX/build-qingqing-release# make geosx_xml_tools
[100%] Generating ../../bin/preprocess_xml, ../../bin/format_xml
Attempting to install packages directly in target python environment...
  geosx_mesh_tools_package
  geosx_xml_tools_package
  hdf5_wrapper_package
  pygeosx_tools_package
Linking key scripts to bin directory...
  preprocess_xml
  (could not find where preprocess_xml is installed)
  format_xml
  (could not find where format_xml is installed)
Done!
[100%] Built target geosx_xml_tools

**Comment by klevzoff** [comment]
Hi @bigmonsterlee,

This issue has been observed when using system-provided `python`. When installing our python packages without root privileges, `pip` installs them in `--user` mode, which puts some executable scripts (`preprocess_xml` and `format_xml`) under `$HOME/.local/bin`. Later, when attempting to find and symlink those scripts, they cannot be located neither in `python` directory (which is just `/usr/bin`) nor by `which` command (the two search methods we use).

A simple workaround I use on my machines is to add the following to `~/.bashrc`:
```bash
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```
Then reset your environment (e.g. by running `source ~/.bashrc`), and run `make geosx_xml_tools` again. Let me know if this helps. Maybe @cssherman has better advice.

**Comment by bigmonsterlee** [comment]
> Hi @bigmonsterlee,
> 
> This issue has been observed when using system-provided `python`. When installing our python packages without root privileges, `pip` installs them in `--user` mode, which puts some executable scripts (`preprocess_xml` and `format_xml`) under `$HOME/.local/bin`. Later, when attempting to find and symlink those scripts, they cannot be located neither in `python` directory (which is just `/usr/bin`) nor by `which` command (the two search methods we use).
> 
> A simple workaround I use on my machines is to add the following to `~/.bashrc`:
> 
> ```shell
> # set PATH so it includes user's private bin if it exists
> if [ -d "$HOME/.local/bin" ] ; then
>     PATH="$HOME/.local/bin:$PATH"
> fi
> ```
> 
> Then reset your environment (e.g. by running `source ~/.bashrc`), and run `make geosx_xml_tools` again. Let me know if this helps. Maybe @cssherman has better advice.

Thanks a lot.
I added the codes to `~/.bashrc` and reset my environment, but the same problem still arose.

**Comment by cssherman** [comment]
Some further reading suggests that there are some platform-specific issues with predicting where the scripts will be installed (see https://discuss.python.org/t/proper-way-to-determine-install-location-of-console-scripts/7188) .  I don't have an ubuntu system available for testing, but it sounds like the scripts may be installed in `/usr/local/bin`.

The step where the install is complaining is meant to create some symbolic links from the packages to the build/bin directory.  If you can locate them on your machine, you can link them manually (`ln -ls /path/to/preprocess_xml /path/to/GEOSX/build-quartz-gcc@8.1.0-release/bin/preprocess_xml`, ...)

**Comment by cssherman** [comment]
@bigmonsterlee  Interesting...  I agree that the issue here is that you are trying to use the system python.  Trying to install packages directly into the system python can isn't recommended because it can sometimes cause unexpected side-effects.

To make things easier, I recommend that you create a python environment that you control.  This could one of the following:

1) A standalone python distribution (see https://towardsdatascience.com/building-python-from-source-on-ubuntu-20-04-2ed29eec152b or https://docs.anaconda.com/anaconda/install/linux/ )
2) A virtual python environment built off of any version of python 3.X you have available.  Assuming that the virtualenv package is installed, you can run something like the following: `/path/to/python -m virtualenv --system-site-packages /path/to/virtualenv/` (replacing the path arguments).  You can then refer to the new python executable or load the environment: `source /path/to/virtualenv/bin/activate`

Once this step is complete, you should run the GEOSX configuration step with this new version of python (or set the PYTHON_POST_EXECUTABLE cmake variable) and re-build the code (see: https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/fileIO/doc/InputXMLFiles.html#setup).  The packages should then be installed in within the environment that you control.

**Comment by cssherman** [comment]
@bigmonsterlee - did this help you resolve the installation issue?

**Comment by bigmonsterlee** [comment]
It worked！
