### ISSUE TITLE
[Bug] Probably a bug in DeadOilFluid::KernelWrapper::computeViscosities?

### ISSUE THREAD

**Issue by wrtobin** [GEOSX/GEOSX#1883]
The function argument `phaseVisc` in the noted function is a `PhaseProp::SliceType`, `PhaseProp` is a `MultiFluidVar` which is defined in a code snippet below. At DeadOilFluid.hpp::303 it is indexed as `&(phaseVisc.derivs)[ip][Deriv::dP]`. The member `MultiFluidVarSlice.derivs` is not an standard array or raw pointer. Nor is the `PhaseProp` passed into `computeViscosities` an array of `PhaseProp`s (where `&(phaseVisc.derivs[ip])[Deriv::dP]` might be reasonable).

Really only `&(phaseVisc.derivs[ip][Deriv::dP])` should make sense here (esp based on usage elsewhere), so long as it is always passing an `ArraySlice` instead of a raw pointer (unless we're assuming the array permutation). But even then we're passing an `ArraySlice*` instead of the slice itself, so then I would assume `phaseVisc.derivs[ip][Deriv::dP]` but that winds up passing a `real64` to the compute function which is invalid for that function so compilation fails. So at least a `real64*` is needed... but that also means we're assuming the underlying permutation... so some revision is needed here unless I'm really missing something (in which case we should document it via comments cause it is definitely non-obvious)

https://github.com/GEOSX/GEOSX/blob/8445c1c2a70eb0bf42a5c25f9c079f71fd16617e/src/coreComponents/constitutive/fluid/DeadOilFluid.hpp#L286-L319

https://github.com/GEOSX/GEOSX/blob/8445c1c2a70eb0bf42a5c25f9c079f71fd16617e/src/coreComponents/constitutive/fluid/MultiFluidUtils.hpp#L89-L110

@francoishamon You edited that line last, any input would be great.

**Comment by klevzoff** [comment]
Indeed, `&(phaseVisc.derivs[ip][Deriv::dP])`, or simply `&phaseVisc.derivs[ip][Deriv::dP]` which is equivalent by operator precedence rules, is supposed to be the correct expression here. I'd actually favor second style more because it eliminates the opportunity for misplacing parenthesis.

As for passing a raw pointer obtained from a slice, it's not safe in general, but in this case all `m_viscosityTables` are univariate functions which only write a single value into their second argument, so it works regardless of the permutation. To make it safe for multivariate functions that produce multiple derivatives, we need a way to produce "ArraySlice with offset" kind of object, or explicitly pass an additional `offset` argument to `TableFunction::KernelWrapper::compute()`... or always pass pointers to stack arrays followed by an explicit copy into target slice.

**Comment by francoishamon** [comment]
Thanks for the catch @wrtobin @klevzoff, my bad, I will fix it

**Comment by francoishamon** [comment]
I am changing this call in PR #1880 to this
https://github.com/GEOSX/GEOSX/blob/41fe68e9efffad07e9451e3e09187780a5962602/src/coreComponents/constitutive/fluid/DeadOilFluid.hpp#L303-L305
by passing a pointer followed by an explicit copy in the target slice for now.
