### ISSUE TITLE
Add ubuntu 22.04 LTS Jammy to travis

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#1889]
New LTS ubuntu 22.04 LTS is out https://releases.ubuntu.com/jammy.
Developers will eventually use it, so we'll have to support in on travis.
The sooner the better.

Not to bloat too much our CI, I think that we can replace one (or more) of our 3 ubuntu 20.04 targets
- Ubuntu (20.04, gcc 9.3.0, open-mpi 4.0.3)
- Ubuntu debug (20.04, gcc 10.3.0, open-mpi 4.0.3)
- Ubuntu (20.04, gcc 10.3.0, open-mpi 4.0.3)

We could add support for `gcc-11` and `gcc-12`.

**Comment by Mohamed-AIDAHI** [comment]
@TotoGaz there also a compilation error of trilinos during the building kokkoscore, i tried using the latest version of trilinos (14.0) and it  successfully built kokkoscore but it failed to build teuchoscore.
 
(g++: warning: : linker input file unused because linking not done
g++: error: : linker input file not found: No such file or directory
make[5]: *** [packages/teuchos/core/src/CMakeFiles/teuchoscore.dir/build.make:132: packages/teuchos/core/src/CMakeFiles/teuchoscore.dir/Teuchos_Details_Allocator.cpp.o] Error 1)

**Comment by TotoGaz** [comment]
Hi @Mohamed-AIDAHI !
Where did you get this 14.0 release from?
Today's https://github.com/trilinos/Trilinos/releases only offers 13.4.0.

**Comment by Mohamed-AIDAHI** [comment]
Hi @TotoGaz 
You are right, i used the version 13.5
