### ISSUE TITLE
[Bug] Poromechanics problems with gravity do not produce expected stress field

### ISSUE THREAD

**Issue by cssherman** [GEOSX/GEOSX#2041]
**Describe the bug**
I noticed some odd behavior in a model with poromechanics + gravity, so I put together a small test problem.  In the example, I have a column of elements, with rollers on the +/-x, +/-y, and -z faces, and a constant pressure (0) on the z+ surface.  The pressure and stress fields are initialized with values from a table (the python script used to build these is included).

The initial stress, pressure, and displacement in the model are:

![initial_stress_displacement](https://user-images.githubusercontent.com/4932756/187798357-1d7a9c74-c51f-4a5e-b142-92c5d1f808ce.png)

Applying either the solid mechanics or fluid solvers *alone*, yields correct looking results:

![final_stress_displacement_mechanics_only](https://user-images.githubusercontent.com/4932756/187798466-884e964d-8974-4dd6-a4e4-4746ebb223e2.png)

However, when the poroelastic solver is applied, the stress/displacement fields do not make sense:

![final_stress_displacement_poroelastic](https://user-images.githubusercontent.com/4932756/187798557-63c2d6e3-7649-47de-85ef-e58886414e2d.png)

**To Reproduce**

See the attached example here.  In the event block, you can change which solvers are applied to the problem and see how the values change.

[poroelastic_gravity.zip](https://github.com/GEOSX/GEOSX/files/9465570/poroelastic_gravity.zip)

**Comment by francoishamon** [comment]
Hello @cssherman 

This is a PR that fixes this issue: https://github.com/GEOSX/GEOSX/pull/1927

We have used it for our poromechanics field test cases with gravity, but I did not manage to merge it yet (mostly because the PR also does the initialization in a not so clean way). The PR changes the formulation of the body force terms and the density terms in the poromechanics solvers (single-phase and multiphase) to make sure that the stress and displacement are correct when you start the simulation with a non-zero stress and pressure field.

When I test the PR for your case with the two options (coupled, and elastic), it gives the correct results:

For coupled:
<img width="150" alt="Screen Shot 2022-09-01 at 11 34 15 AM" src="https://user-images.githubusercontent.com/20196406/187808777-b6b7382a-637a-4b89-b0d8-7922aa3b613a.png"><img width="150" alt="Screen Shot 2022-09-01 at 11 33 44 AM" src="https://user-images.githubusercontent.com/20196406/187808785-70130cc3-e8c8-4895-8ffd-379e6e4181ae.png">

For elastic:
<img width="150" alt="Screen Shot 2022-09-01 at 11 38 59 AM" src="https://user-images.githubusercontent.com/20196406/187808796-6887b47d-bdde-4d92-87c9-5c573d9a16a5.png"><img width="150" alt="Screen Shot 2022-09-01 at 11 38 46 AM" src="https://user-images.githubusercontent.com/20196406/187808804-ffb59a9e-f0b1-44f9-bce8-35c07a1ba5fb.png">

I am going to fix this issue with a clean new PR if that is ok

**Comment by cssherman** [comment]
Great, thanks!
