### ISSUE TITLE
Regular input file for 'thermalMultiphaseFlow/co2_thermal_obl_3d.xml' case 

### ISSUE THREAD

**Issue by ajikmr** [GEOSX/GEOSX#2087]
Hello.
I was looking at OBL based example case: 'inputFiles/thermalMultiphaseFlow/co2_thermal_obl_3d.xml'. Could you please add regular simulation version where OBL approach is not used? This will help in one-to-one comparison.
Thanks,
Ajit

**Comment by francoishamon** [comment]
Hello @ajikmr,
You can adapt [this integrated test](https://github.com/GEOSX/GEOSX/blob/develop/inputFiles/thermalMultiphaseFlow/co2_thermal_2d.xml) to match the `co2_thermal_obl_3d` integrated test based on OBL. The results should be close but not exactly the same since the thermal PVT used in the OBL tables of this example is slightly more sophisticated than what we have in the non-OBL version (for instance, OBL has water evaporation in the CO2 phase).

**Comment by ajikmr** [comment]
Hello @francoishamon ,
Thanks for your reply. Just to confirm few points:
i. fluid property: '2d' case has two components (CO2, H2O), while 'obl_3d' case has three components (CO2, C1, H2O). Though, I can add component property values from literature.
ii. relPerm values: RelPerm curve details will be just copied over.
iii. Fluid thermal conductivity: thermalCond for fluid will be copied over.
iv. ThermalCompositionalMultiphase model will be used
