### ISSUE TITLE
when I running the unit tests, some of them failed

### ISSUE THREAD

**Issue by Chaojie-Di** [GEOSX/GEOSX#2111]
171: error: Could not open file /home/chaojie/code/GEOSX/build-your-platform-release/html/doxygen_output/latex/Makefile for writing
171/171 Test #171: testDoxygenCheck .....................................***Failed    2.57 sec

99% tests passed, 1 tests failed out of 171

Total Test time (real) =  76.40 sec

The following tests FAILED:
	171 - testDoxygenCheck (Failed)

**Comment by klevzoff** [comment]
This is usually caused by one of the tools Doxygen uses (`dot` for rendering graphs or `latex` for formulas) not being installed on the system. You can check by running the test with verbose output:
```
ctest -V -R Doxygen
```
This is absolutely not critical and has no impact on code correctness, but if it annoys you consider installing those tools if possible.

**Comment by Chaojie-Di** [comment]
> This is usually caused by one of the tools Doxygen uses (`graphviz`/`dot` for rendering graphs or `latex` for formulas) not being installed on the system. You can check by running the test with verbose output:
> 
> ```
> ctest -V -R Doxygen
> ```
> 
> This is absolutely not critical and has no impact on code correctness, but if it annoys you consider installing those tools if possible.

**Comment by Chaojie-Di** [comment]
Thank you. I will install those tool.
