### ISSUE TITLE
Non-matching index types. ParMETIS must be built with 64-bit indices

### ISSUE THREAD

**Issue by matteoicardi** [GEOSX/GEOSX#2146]
I get this error when compiling on a Mac M1 using the config file

I tried to disable ParMETIS from CMake but it still tries to compile the ParMETIS interface

```
[ 18%] Building CXX object coreComponents/mesh/CMakeFiles/mesh.dir/generators/ParMETISInterface.cpp.o
/Users/xxxxxx/geosx/GEOSX/src/coreComponents/mesh/generators/ParMETISInterface.cpp:38:1: error: static_assert failed due to requirement 'std::is_same<int, long long>::value' "Non-matching index types. ParMETIS must be built with 64-bit indices."
static_assert( std::is_same< idx_t, int64_t >::value,
```

**Comment by wrtobin** [comment]
@bmhan12 This looks like a cmake optional tpl being handled incorrectly. IIRC our optional tpls can be activated if they are found even if we don't enable them.

**Comment by bmhan12** [comment]
> @bmhan12 This looks like a cmake optional tpl being handled incorrectly. IIRC our optional tpls can be activated if they are found even if we don't enable them.

I think we're treating ParMETIS as a required dependency:
https://github.com/GEOSX/GEOSX/blob/15de98b7259aa676d9d8cbcaacfcd30baa6b3347/src/coreComponents/mesh/CMakeLists.txt
So this interface (or at least this file) will always be compiled, regardless if enabled/disabled.
Should we be guarding ParMETIS as an optional dependency?

As for the error, I believe the tarball we are using forces int64, so it should not error there.
https://github.com/GEOSX/thirdPartyLibs/blob/3241d48197b8c7b6a21383104adbd3fa47c92747/CMakeLists.txt#L626-L630

**Comment by wrtobin** [comment]
No reason to demote metis/parmetis to optional, I was just remembering I've run into optional dependencies activating erroneously and thought it might be related.

Possibly the parmetis being found could be a system install? Though since its on the M1 presumably they'll only have their own version installed. Does the cmake config report anything about the parmetis install other than the location?

**Comment by TotoGaz** [comment]
> I was just remembering I've run into optional dependencies activating erroneously

IIRC it's not erroneously, it was explicitly designed to behave like this.

**Comment by matteoicardi** [comment]
I have  indeed Metis installed through homebrew and it seems to be 32bit but the METIS include and Lib folder are correct in ccmake (pointing to the thirdparty folder)

**Comment by matteoicardi** [comment]
sorted! for some reason I had the CPATH and LIBRARY_PATH pointing to homebrew libraries! Thanks

**Comment by TotoGaz** [comment]
Hello @matteoicardi glad you solved your problem!
Just to warn you, apple M1 is best effort, close to nobody uses it and it's really not granted that it's working properly (sometimes very small details just blows it up).
Be sure to run the tests and be cautious when it comes to analyzing the results.
In the long term, considering a linux solution could be an interesting move.

**Comment by wrtobin** [comment]
> > I was just remembering I've run into optional dependencies activating erroneously
> 
> IIRC it's not erroneously, it was explicitly designed to behave like this.

Specifically when a user explicitly sets an ENABLE_XXX optional TPL flag to FALSE, and we still configure with it if it is found?

I would consider that an error, since there are cases when a developer / user will want to disable something that is available on their system (really more developers).

For instance, while I was working on the HIP build on crusher, there were known issues with having openmp active at the same time as using HIP/ROCM. Explicitly setting ENABLE_OPENMP to FALSE in the host-config doesn't actually disable openmp, so I still encountered issues until I allowed actually turning it off (since its always going to be found on basically all of our hpc platforms when we setup blt). 

This specific sort of case probably will never effect a user, but I still find explicitly disabling an option not actually disabling it to be unintuitive.

**Comment by wrtobin** [comment]
In my case the ENABLE_OPENPM flag didn't do anything. If openmp was found, we used it. If it wasn't found, we didn't. So why have the flag? 

If optional TPLs are always used when found having the host-config flags isn't necessary.

**Comment by TotoGaz** [comment]
I kind of agree but this is what I understood from this [thread](https://github.com/GEOSX/GEOSX/pull/1204#discussion_r527200974) during the review.
Am I wrong?

**Comment by wrtobin** [comment]
Simply not specifying the `_DIR` for the TPL is fine for TPLs we build and control, but definitely can't work in all cases for system TPLs that might be found by e.g. blt.

**Comment by TotoGaz** [comment]
> Simply not specifying the `_DIR` for the TPL is fine for TPLs we build and control, but definitely can't work in all cases for system TPLs that might be found by e.g. blt.

In an environment where we share the burden of building the TPLs for a community (typically on clusters), we build all the TPLs and the devs pick up what they want or need. Furthermore, you may want to switch to different contexts, depending on your task: long term dev or short term bugfix e.g.

**Comment by TotoGaz** [comment]
> I just think there are different classes of TPLs...

There are indeed [prerequisites and TPLs](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/buildGuide/Index.html), and I think they can be optional and mandatory.
Actually the situation is quite simple
- If they are mandatory, there should be no `ENABLE_*`
- If they are optional, there should be an `ENABLE_*` and we should respect the `ENABLE_*` choice in the configuration.
