### ISSUE TITLE
incorrect assumption (3-shared nodes) about element-face connectivity for prisms

### ISSUE THREAD

**Issue by jeannepellerin** [GEOSX/GEOSX#2222]
**Describe the bug**

Incomplete CellElementRegion definition in the input XML file makes GEOSX crash.

As a user I expect GEOSX to return a meaningful error and not crash.

The result of the dynamic_cast done in getGroup function called line 493 of src/coreComponents/mesh/generators/CellBlockManager.cpp should be checked.

**Crashing ranks** 
 
Received signal 11: Segmentation fault

Frame 0: /lib64/libc.so.6
Frame 1: __dynamic_cast
Frame 2: geosx::CellBlock& geosx::dynamicCast<geosx::CellBlock&, geosx::dataRepository::Group>(geosx::dataRepository::Group&)
Frame 3: geosx::CellBlock& geosx::dataRepository::Group::getGroup<geosx::CellBlock, int>(int const&)
Frame 4: geosx::fillElementToEdgesOfCellBlocks(LvArray::ArrayOfArraysView<int const, int const, true, LvArray::ChaiBuffer> const&, geosx::dataRepository::Group&)
Frame 5: geosx::CellBlockManager::buildMaps()
Frame 6: geosx::VTKMeshGenerator::generateMesh(geosx::DomainPartition&)
Frame 7: geosx::MeshManager::generateMeshes(geosx::DomainPartition&)
Frame 8: geosx::ProblemManager::generateMesh()
Frame 9: geosx::ProblemManager::problemSetup()
Frame 10: geosx::GeosxState::initializeDataRepository()
Frame 11: main
Frame 12: __libc_start_main
Frame 13: /workrd/SCR/GEOSX/install/gcc8/GEOSX-a31068c/bin/geosx

**Other ranks**

Failure when gathering information

Frame 6: geosx::vtk::printMeshStatistics(vtkDataSet&, std::map<geosx::ElementType, std::unordered_map<int, std::vector<long long, std::allocator<long long> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, std::vector<long long, std::allocator<long long> > > > >, std::less<geosx::ElementType>, std::allocator<std::pair<geosx::ElementType const, std::unordered_map<int, std::vector<long long, std::allocator<long long> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, std::vector<long long, std::allocator<long long> > > > > > > > const&, ompi_communicator_t*)
Frame 7: geosx::VTKMeshGenerator::generateMesh(geosx::DomainPartition&)
Frame 8: geosx::MeshManager::generateMeshes(geosx::DomainPartition&)
Frame 9: geosx::ProblemManager::generateMesh()
Frame 10: geosx::ProblemManager::problemSetup()
Frame 11: geosx::GeosxState::initializeDataRepository()
Frame 12: main
Frame 13: __libc_start_main
Frame 14: /workrd/SCR/GEOSX/install/gcc8/GEOSX-a31068c/bin/geosx

**Comment by jeannepellerin** [comment]
It is extremely frustrating to have no list of the expected CellBlocks names. There are 20 regions, 7 different types of cells in this model. If that is the cause of the crash.

**Comment by francoishamon** [comment]
I compiled GEOSX with the bound checks activated, and I got the actual error that causes the crash:
```
***** ERROR                                                                                                                                                                              
***** LOCATION: GEOSX/src/coreComponents/LvArray/src/indexing.hpp:209                                                                                                
***** Controlling expression (should be false): invalidIndices( dims, indices ... )                                                                                                      
Invalid indices. dimensions = { 13747, 15 } indices = { 2035, 15 }                                                                                                                       
                                                                                                                                                                                         
** StackTrace of 13 frames **                                                                                                                                                            
Frame 1: __kmp_invoke_microtask                                                                                                                                                          
Frame 2: __kmp_fork_call                                                                                                                                                                 
Frame 3: __kmpc_fork_call                                                                                                                                                                
Frame 4: geosx::fillElementToEdgesOfCellBlocks(LvArray::ArrayOfArraysView<int const, int const, true, LvArray::ChaiBuffer> const&, geosx::dataRepository::Group&)                        
Frame 5: geosx::CellBlockManager::buildMaps()                                                                                                                                            
Frame 6: geosx::VTKMeshGenerator::generateMesh(geosx::DomainPartition&)                                                                                                                  
Frame 7: geosx::MeshManager::generateMeshes(geosx::DomainPartition&)                                                                                                                     
Frame 8: geosx::ProblemManager::generateMesh()                                                                                                                                           
Frame 9: geosx::ProblemManager::problemSetup()                                                                                                                                           
Frame 10: geosx::GeosxState::initializeDataRepository()                                                                                                                                  
Frame 11: main                                                                                                                                                                           
Frame 12: __libc_start_main                                                                                                                                                                                                                                                                    
=====       
```
The problem is the following: GEOSX is trying the fill the element-to-edge map of a pentagonal prism. For this element type, GEOSX expects 15 edges, but finds a 16th one coming from the face-to-edge map. So, when we check if this 16th edge is already in the element-to-edge map [here](https://github.com/GEOSX/GEOSX/blob/88f9773654a2d9c4086aabb9b623479e6778c176/src/coreComponents/mesh/generators/CellBlockManager.cpp#L526), there is an out-of-bound access, and a crash.

So, the problem either comes from the edge building in GEOSX, or from the PEBI mesh. We have the indices of the problematic faces and edges, so we can start debugging by looking [in this function](https://github.com/GEOSX/GEOSX/blob/88f9773654a2d9c4086aabb9b623479e6778c176/src/coreComponents/mesh/generators/CellBlockManager.cpp#L585) to understand where the problem comes from.

**Comment by jeannepellerin** [comment]
The problem comes from the mesh. Its connectivity is not correct.

GEOSX must check the input mesh and cell individually. There is no choice.

For example from the problematic mesh, one cell with 10 points (a pentagonal prism theoretically has 10 points whose coordinates are fine.

The faces defined are not the one expected. 
There are 7 faces, one with 7 points, one with 2 points ..... 
CONNECTIVITY 
7 5 2 3 6 8 0 5 
5 1 9 7 4 4
2 0 1 
5 4 0 8 9 1
4 8 6 7 9
4 6 3 4 7 
4 3 2 5 4

**Comment by francoishamon** [comment]
Ok thanks for the investigation. We can add a check for this in the mesh doctor

**Comment by AntoineMazuyer** [comment]
Hi,

@jeannepellerin, does it appear for every pentagonal prism of the mesh ?

Best,

**Comment by AntoineMazuyer** [comment]
``> 5 1 9 7 4 4

If the connectivity were written in a file version of vtk > 5.2, it has to be read like this

```
7             # number of faces
5 2 3 6 8 0   # first face has 5 points
5 5 1 9 7 4   # second face has 4 points
4 2 0 1 5 
4 0 8 9 1
4 8 6 7 9
4 6 3 4 7
4 3 2 5 4
```

https://discourse.vtk.org/t/polyhedral-cell/8237

So no problem with this cell.

**Comment by AntoineMazuyer** [comment]
Are we expecting issue with cells like that ?

![image](https://user-images.githubusercontent.com/32493098/210867380-3dfaba0d-ba82-44a9-a57a-b915f70241b5.png)

**Comment by francoishamon** [comment]
My understanding of this problem is the following:

The two cells are sharing two co-planar faces. In the image that Antoine posted, we see two 5-node faces, one belonging to the blue cell, and another belonging to the orange cell. These two faces are different, but they have 3 nodes in common. In GEOSX, my understanding is that in our face building procedure, two faces sharing 3 nodes can be considered equal for the face matching [here](https://github.com/GEOSX/GEOSX/blob/6b4c58e595e80508c1150b71be9aabbb3d1b0661/src/coreComponents/mesh/generators/CellBlockManager.cpp#L253). So, in some cases, GEOSX might think that the two 5-node faces are equal, which messes up the element-to-face map.

To make this concrete, here is a reproducer of the problem using the configuration that Antoine posted:

Mesh and xml: [smallModel.zip](https://github.com/GEOSX/GEOSX/files/10355623/smallModel.zip)

After the face matching, GEOSX finds that cell 0 and cell 2 have 3 faces in common in the element-to-face map constructed in `buildFaceMaps`: 
- The two coplanar faces with 4 nodes (face ids: 19 and 21), which is expected
- One 5-node face (face id: 32), which is impossible, but happens because the 3 shared nodes have confused the face matching procedure (I think)

An as a result GEOSX crashes later, when it uses the element-to-face map to construct the element-to-edge map.

I may be wrong, so I am looking for help before diving into the face matching code. Can anyone confirm that my logic is correct, i.e., that two faces can be "matched" if they share 3 nodes? 

@TotoGaz @castelletto1 @corbett5 @klevzoff @rrsettgast

**Comment by corbett5** [comment]
Yeah I'm pretty sure my logic was if two faces share three nodes they're equal. I guess it's worked up until now haha.

**Comment by klevzoff** [comment]
@francoishamon your analysis seems correct to me. 

As long as matching faces can be identified by a fixed (compile-time) number of matching nodes, we can adjust the current algorithm slightly to handle it. If full matching of arbitrary-length node lists is required for full correctness, we may have to use additional data structures, e.g. instead of storing node indices inline in `NodesAndElementOfFace`, have it point into another `ArrayOfArrays` storing sorted node lists for each (duplicate) face, which will make comparisons more expensive due to memory indirection.

**Comment by TotoGaz** [comment]
Hi there, #1418 had modified slightly the structure by storing an arbitrary number of nodes in `NodesAndElementOfFace` to make it support "more complex situations" like the current one.
It has been reverted in #1847 for the sake of performance.

**Comment by klevzoff** [comment]
> Hi there, #1418 had modified slightly the structure by storing an arbitrary number of nodes in `NodesAndElementOfFace` to make it support "more complex situations" like the current one.
> It has been reverted in #1847 for the sake of performance.

Yes, we can re-implement something like this, but instead of storing a node list in a separate allocation in each entry `NodesAndElementOfFace` (which was the ultimate cause of slowdown) we could pack them in a single `ArrayOfArays` that will be built by a RAJA kernel. This might be reasonably fast I think; although the memory indirection will slow it down compared to current state, but it shouldn't be dramatic.

**Comment by corbett5** [comment]
@jeannepellerin can you try out my new branch, it should fix the problem.

https://github.com/GEOSX/GEOSX/pull/2321

I tried out the xml that @francoishamon posted, and I get past the mesh building stage, but it crashes with what I hope is an unrelated error.

```
***** ERROR
***** LOCATION: /usr/WS2/corbett5/geosx/GEOSX/src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp:129
***** Controlling expression (should be false): fluidName.empty()
***** Rank 0: Fluid model not found on subregion 1_pentagonalPrisms
```
