### ISSUE TITLE
"createKernelWrapper" functionality

### ISSUE THREAD

**Issue by ver2king** [GEOSX/GEOSX#2303]
I have been trying to implement some custom fluid models in geosx.  I noticed in geosx that many code files exist with the "createKernelWrapper" functionality (not limited to fluid/constitutive). For example, in the file DeadOilFluid.hpp: 

  /**
   * @brief Create an update kernel wrapper.
   * @return the wrapper
   */
  KernelWrapper **createKernelWrapper()**;

I tried to grasp an idea of whether this functionality is inherited from any other header files, or from any other files in geosx that I may be unaware of.

**Comment by klevzoff** [comment]
Hi @ver2king,

The goal of this member function is to allow each constitutive model to control the creation of its "kernel wrapper", which is simply our term for a representation of the model suitable for in-kernel computation (i.e. one that can be captured in lambdas, copied into GPU kernel argument space and called on device). Since these wrappers are different for each model and need different arguments in their constructors, the model itself is responsible for passing all the necessary data to a new wrapper instance.

The implementation of this function is placed in the model's `.cpp` file and is typically trivial (just calling the wrapper's constructor), although some custom logic could be included there if needed. For example, in case of `DeadOilFluid`, it's this:
https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/constitutive/fluid/DeadOilFluid.cpp#L153

**Comment by ver2king** [comment]
Also relevant to the KernelWrapper, in many .hpp files (e.g., DeadOilFluid.hpp for illustration again), this code snipper exists:

GEOSX_HOST_DEVICE
inline void
DeadOilFluid::KernelWrapper::
  update( localIndex const k,
          localIndex const q,
          real64 const pressure,
          real64 const temperature,
          arraySlice1d< geosx::real64 const, compflow::USD_COMP - 1 > const & composition ) const
{
  compute( pressure,
           temperature,
           composition,
           m_phaseFraction( k, q ),
           m_phaseDensity( k, q ),
           m_phaseMassDensity( k, q ),
           m_phaseViscosity( k, q ),
           m_phaseEnthalpy( k, q ),
           m_phaseInternalEnergy( k, q ),
           m_phaseCompFraction( k, q ),
           m_totalDensity( k, q ) );
}

May someone clarify the uses of "localIndex" k & q? I raise this concern since I am unable to link/interpret these variables with any others within the relevant .hpp files. or any other #include .hpp files.

**Comment by klevzoff** [comment]
We should give those parameters proper names. Typically `k` = `elementIndex` and `q` = `quadraturePointIndex`.

**Comment by ver2king** [comment]
I appreciate all of your responses @klevzoff. Just a side request, may you look into issue #2310 quickly and, if possible, assign/refer anyone who is able to clarify that issue? I am the one who opened it and still waiting for a solid explanation.

For this issue, as indicated, I am satisfied with your responses and therefore I shall close it.
