### ISSUE TITLE
Use umpire memcpy for contiguous device packing/unpacking.

### ISSUE THREAD

**Issue by corbett5** [GEOSX/GEOSX#719]

**Comment by wrtobin** [comment]
Closing due to the most recent round of device packing optimizations.

`memcpy` - based device packing proved to be significantly less efficient than assignment-based packing on properly memory aligned types.

**Comment by corbett5** [comment]
This was more for doing a copy of an `Array` wholesale and not when packing by index. I'll eat my hat if it's faster to pack an entire Array by launching a kernel than it is to call memcpy.

**Comment by wrtobin** [comment]
So presumably for packing entire arrays on host? Yeah straight memcpy in that case would definitely be the way to go.

All of the device packing we've evaluated has been by index, since that is the vast majority of our device packing in practice (I'm unaware of if/where we pack whole arrays on device).

I did experiment with an implementation to pack index slices by memcpy when possible ( for the subset of possible cases which I was actually evaluating ), but that wound up being essentially the same as using forValuesInSlice with memcpy IIRC, and assignment beat both.

Copying a whole array on device... I'd think just a memcpy would be faster, but given the speedup we saw with the index-based memcpy -> assignment change I'd definitely benchmark it to be sure.
